resources:
- name: charts-upstream
  type: git
  source:
    uri: https://github.com/helm/charts

- name: charts-fork
  type: git
  source:
    uri: https://((github-token))@github.com/concourse/charts
    branch: master

- name: charts-fork-merged
  type: git
  source:
    uri: https://((github-token))@github.com/concourse/charts
    branch: merged

- name: charts-fork-maintenance
  type: git
  source:
    uri: https://((github-token))@github.com/concourse/charts
    branch: maintenance

- name: charts-fork-gh-pages
  type: git
  source:
    uri: https://((github-token))@github.com/concourse/charts
    branch: gh-pages

- name: maintenance-image
  type: registry-image
  source:
    repository: cirocosta/git
    username: ((docker-user))
    password: ((docker-password))

jobs:
- name: maintenance-image
  plan:
  - get: charts-fork-maintenance
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/builder
      params:
        REPOSITORY: cirocosta/maintenance-image
        CONTEXT: ./charts-fork-maintenance
      inputs:
      - name: charts-fork-maintenance
      outputs:
      - name: image
      run:
        path: build
  - put: maintenance-image
    params:
      image: image/image.tar
    get_params:
      format: oci

- name: bump-fork
  plan:
  - aggregate:
    - get: charts-upstream
      trigger: true
  - put: charts-fork
    inputs: [ charts-upstream ]
    params:
      repository: ./charts-upstream

- name: update-hosted-helm-repository
  plan:
  - aggregate:
    - get: maintenance-image
      passed: [ maintenance-image ]
      trigger: true
    - get: charts-fork
      passed: [ bump-fork ]
      trigger: true
    - get: charts-fork-maintenance
      trigger: true
    - get: charts-fork-gh-pages
  - task: produce
    image: maintenance-image
    config:
      platform: linux
      inputs:
      - name: charts-fork
      - name: charts-fork-gh-pages
        path: repository
      - name: charts-fork-maintenance
      outputs:
      - name: repository
      params:
        CHART_DIR: ./charts-fork/stable/concourse
        DESTINATION_DIR: ./repository
      run:
        path: /bin/bash
        args:
        - -c
        - -e
        - |
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

          helm init --client-only
          helm repo remove local
          helm repo update
          helm package -u -d $DESTINATION_DIR $CHART_DIR
          helm repo index $DESTINATION_DIR

          cd $DESTINATION_DIR
          git config --global user.name "Ciro S. Costa"
          git config --global user.email "cscosta@pivotal.io"
          git add --all
          git commit -m "[maintenance] bump"

  - put: charts-fork-gh-pages
    inputs: [ repository ]
    params:
      repository: ./repository

- name: run-maintenance
  plan:
  - aggregate:
    - get: maintenance-image
      passed: [ maintenance-image ]
      trigger: true
    - get: charts-fork-maintenance
      trigger: true
    - get: charts-fork
      passed: [ bump-fork ]
      trigger: true
  - task: run
    image: maintenance-image
    config:
      platform: linux
      inputs:
      - name: charts-fork-maintenance
        path: .
      outputs:
      - name: repository
        path: .
      run:
        path: /bin/sh
        args:
        - -c
        - -e
        - |
          ./update-merged-branch.sh

          git config user.name "Ciro S. Costa"
          git config user.email "cscosta@pivotal.io"
          git add --all .
          git commit -m "[maintenance] bumps concourse version"

  - put: charts-fork-merged
    inputs: [ result ]
    params:
      repository: ./result
      force: true

